# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm-publish

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm publish
      run: |
        git config --local user.email "qylinxia@qq.com"
        git config --local user.name "Aaronlamz"
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        npm version patch && git push --follow-tags && npm publish
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

